import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>红楼梦</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div><h1>红楼梦 Dream of Red Mansions stone</h1></div>

        <div className={styles.center}>

          <div><Image
            className={styles.logo}
            src="/images/cover.jpeg"
            alt="HongLouMeng Cover"
            width={500}
            height={300}
          /></div>
        </div>

        <div className={styles.grid}>
          <Link
            href="/modelHTML/index.html"
            className={styles.card}
            target="_blank"
            alt="Stones Archi Model HTML Report"
            rel="noopener noreferrer"
          >
            <h2>
              红楼梦HTML报告 <span>-&gt;</span>
            </h2>
            <p>
              View model in HTML format
            </p>
          </Link>

          <Link
            href="/model/stones.archimate"
            className={styles.card}
            target="_blank"
            alt="Stones Archi Model File"
            rel="noopener noreferrer"
          >
            <h2>
              红楼梦 Archi Model <span>-&gt;</span>
            </h2>
            <p >
              Download Model Source File
            </p>
          </Link>

          <Link
            href="https://www.archimatetool.com/download/"
            className={styles.card}
            target="_blank"
            alt="Archi Model"
            rel="noopener noreferrer"
          >
            <h2>
              ArchiMate Tool <span>-&gt;</span>
            </h2>
            <p>
              Download latest Archi tool for modeling
            </p>
          </Link>

        </div>
      </main>
    </>
  )
}
